### PR TITLE
numpy 1.13

### PR DESCRIPTION
**Pull request by ocefpaf**
Adds `numpy 1.13` to the build matrix

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf

Somehow within the `numpy.distutils` processing `sys.base_prefix` is picked up. But this was introduced first in python3.3. It's not really clear, if `pytmatrix` needs a change, or this is a bug with `numpy.distutils.mingw32ccompiler` [_check_for_import_lib()](https://github.com/numpy/numpy/blob/f6fe0239599f7846168a01f9f64ea74e39c49236/numpy/distutils/mingw32ccompiler.py#L429).

To my understanding, this is is most likely a bug, because there is no version checking whatsoever before using `sys.base_prefix`. 

See https://github.com/numpy/numpy/issues/9276

**Comment by kmuehlbauer** [comment]
@ocefpaf This was already reported with https://github.com/numpy/numpy/issues/9017. There is also a patch suggested. But we would need to patch cf-numpy. Suggestions?

**Comment by kmuehlbauer** [comment]
@ocefpaf I have created the patch according to https://github.com/numpy/numpy/issues/9017#issuecomment-297957150.

There is no response yet, how numpy-devs will handle this. Do you see any chance, that CF can patch numpy this way?

[base_prefix_in_sys_is_for_python____3_3___cherry_picked_from_commit_d4cdf30_.txt](https://github.com/conda-forge/pytmatrix-feedstock/files/1090719/base_prefix_in_sys_is_for_python____3_3___cherry_picked_from_commit_d4cdf30_.txt)

**Comment by ocefpaf** [comment]
> Do you see any chance, that CF can patch numpy this way?

I think we can merge that even if it is ignored by upstream devs b/c we do have a use for it right now.

I will take a look at the patch soon. Thanks @kmuehlbauer!

**Comment by kmuehlbauer** [comment]
See https://github.com/numpy/numpy/pull/9280, so you might just use those changes.

**Comment by kmuehlbauer** [comment]
@ocefpaf I updated the patch according to https://github.com/numpy/numpy/pull/9280.

[_BUG__Make_extensions_compilable_with_MinGW_on_Py2_7__The_original_changeset_1c8ecc7_to_ma.txt](https://github.com/conda-forge/pytmatrix-feedstock/files/1091228/_BUG__Make_extensions_compilable_with_MinGW_on_Py2_7__The_original_changeset_1c8ecc7_to_ma.txt)

**Comment by ocefpaf** [comment]
Thanks @kmuehlbauer! Do you want to send a PR to the `numpy-feedstock` or should I do it?

**Comment by kmuehlbauer** [comment]
@ocefpaf I can do! just a minute or two...

**Comment by kmuehlbauer** [comment]
@ocefpaf 😟 This would not make any sense, because in cf-numpy there is no windows build due to missing `openblas`. I didn't thought about we using `numpy` from `defaults` here. So we are stuck here. WDYT?

**Comment by ocefpaf** [comment]
> @ocefpaf 😟 This would not make any sense, because in cf-numpy there is no windows build due to missing `openblas`. I didn't thought about we using `numpy` from `defaults` here. So we are stuck here. WDYT? 

It is still worth it b/c my plan is to try to get continuum attention and see if they can use our recipe.

Also, I do build a numpy for Windows with `mkl`  in a private channel for my day job. That build is based on `conda-forge`'s recipe.

(Maybe it is time to do the same in conda-forge instead o waiting for `openblas` there.)

**Comment by kmuehlbauer** [comment]
see https://github.com/conda-forge/numpy-feedstock/pull/51

**Comment by ocefpaf** [comment]
Closing this. I'll try another approach for the `numpy` matrix here.

**Pull request closed without merging**
