### PR TITLE
MNT: Rerender with conda-smithy 1.7.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
I didn't skip the CI's to test for any problems. Also to see if #4 is still due.

**Comment by kmuehlbauer** [comment]
@ocefpaf @jakirkham

It seems, that issue https://github.com/conda-forge/conda-forge.github.io/issues/252 is reappearing here for the python2.7 builds: 
https://ci.appveyor.com/project/conda-forge/pytmatrix-feedstock/build/1.0.14
https://ci.appveyor.com/project/conda-forge/pytmatrix-feedstock/build/1.0.14/job/5s2r0d74ugjhvqpa

I restarted appveyor to cancel out spurious failure, but it would be nice if someone could take a closer look.

**Comment by kmuehlbauer** [comment]
Uh, oh, it seems, that the rerendering with smithy 1.7.0 didn't apply the conda 4.1.12 activation changes. Shall I add that manually?

**Comment by ocefpaf** [comment]
Let me try to rerender that for you. (I am away from my laptop now but I
can do that soon.)

**Comment by kmuehlbauer** [comment]
@ocefpaf I canceled the build until you get your hands on it...

**Comment by kmuehlbauer** [comment]
@ocefpaf After updating/reinstalling some of my conda (root) packages, the rerendering worked (afaict). Can you have another look, or two and merge if you are fine with the changes?

**Comment by ocefpaf** [comment]
Looks good. (Sorry I could not get to it before you but I am glad you have your rerendering capabilities back :wink:)

**Pull request merged**
