### PR TITLE
inspect linkages

### PR DESCRIPTION
**Pull request by ocefpaf**
@kmuehlbauer `libquadmath` in not present in `libgfortran` on Linux, but it is on `OS X`. I also added the inspect linkages command so we can check what is being linked there at the end of the build.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Thanks @ocefpaf. I'll be not able to dig into the failing test and the quadmath issue the next few weeks. 

What are the prospectives of having quadmath? Need conda-forge packaged gcc, right?

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf. I'll be not able to dig into the failing test and the quadmath issue the next few weeks. 

@kmuehlbauer not sure what test failed. Linux is fine b/c `libquadmath` is in `gcc`/`libgcc` and `OS X` should be OK too. (The builds that finished so far are OK.)

> What are the prospectives of having quadmath? Need conda-forge packaged gcc, right?

The only "problem" that we have is that we need to add `libgcc` on Linux instead of only `libgfortran` for `OS X`. (Which would not be a problem if we had a consistent use of `gcc`, but by having `libgcc` available at run time here someone might accidentally link C++ things to `libstdc++` and mess things up like what happened with `numpy`+`openblas`.)

However, nothing is built against `pytmatrix`, so I believe we are good. (I never added `libgcc` to anything that is at the bottom of our stack and the `numpy`+`openblas` took some convincing but they finally fixed it.)

**Comment by kmuehlbauer** [comment]
> However, nothing is built against pytmatrix, so I believe we are good. (I never added libgcc to anything that is at the bottom of our stack and the numpy+openblas took some convincing but they finally fixed it.)

Yes, `pytmatrix` is more or less standalone.

**Comment by kmuehlbauer** [comment]
@ocefpaf FYI: There was one AppVeyor build failing due to some temporary download problem. I tried to retrigger this particular build, but now everything gets rebuild.

Anyway, this is LGTM.

**Comment by ocefpaf** [comment]
@kmuehlbauer the result of the `conda-inspect` can be seen [here](https://travis-ci.org/conda-forge/pytmatrix-feedstock/jobs/148130225#L1198).

But while looking for it I noticed that there is a test failure and `Travis-CI` is still passing. Weird...

```shell
======================================================================
ERROR: test_adaptive_orient (pytmatrix.test.test_tmatrix.TMatrixTests)
Test an adaptive orientation averaging case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pytmatrix/test/test_tmatrix.py", line 107, in test_adaptive_orient
    (S, Z) = tm.get_SZ()
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pytmatrix/tmatrix.py", line 319, in get_SZ
    (self._S, self._Z) = self.get_SZ_orient()
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pytmatrix/tmatrix.py", line 309, in get_SZ_orient
    (self._S_orient, self._Z_orient) = self.orient(self)
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pytmatrix/orientation.py", line 102, in orient_averaged_adaptive
    lambda x: 0.0, lambda x: 180.0, (i,j,True))[0]/360.0
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 495, in dblquad
    return nquad(func, [lambda x: [gfun(x), hfun(x)], [a, b]], args=args)
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 705, in nquad
    return _NQuad(func, ranges, opts, full_output).integrate(*args)
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 760, in integrate
    **opt)
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 315, in quad
    points)
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 380, in _quad
    return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 749, in integrate
    low, high = fn_range(*args)
TypeError: <lambda>() takes exactly 1 argument (4 given)
```

**Comment by kmuehlbauer** [comment]
Yes, that is the one error I mentioned above. Will have to look into this locally.

**Comment by ocefpaf** [comment]
Ah! The green `Travis` totally fooled me.

**Comment by kmuehlbauer** [comment]
@ocefpaf 

I traced this down to some issue with the new `scipy 0.18.0`. It works with `scipy 0.17.1`. Maybe something changed in the calling convention (indicated by the weird lambda-error). But that's just guesswork.

**Comment by ocefpaf** [comment]
You can pin to an older SciPy if you wish and adapt that to the new one later when you have more time.

**Comment by kmuehlbauer** [comment]
How do I pin scipy to use not 0.18.0 but be a little less stringent for the former versions?

**Comment by ocefpaf** [comment]
Adding `scipy < 0.18.0` should do it.

**Comment by kmuehlbauer** [comment]
> Adding scipy < 0.18.0 should do it.

ahh, easy as ever...

**Comment by ocefpaf** [comment]
Note that you need to add that to `run` and `build` requirements and I believe I made a mistake above, you probably need to remove the space between the the inequality and the version number: `scipy <0.18.0` (untested).

**Pull request merged**
