### PR TITLE
Test Win

### PR DESCRIPTION
**Pull request by ocefpaf**
@kmuehlbauer I no longer have a Windows VM to test the builds. So ignore this until I ping you for a review b/c there will be changes (a lot of them :grin:).

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf Crazy stuff, py27 and py34 working on first attempt. :tada:

**Comment by ocefpaf** [comment]
@kmuehlbauer `mingwpy` is not available on Python 3.5 yet... So I guess that is the best we can right now.

**Comment by kmuehlbauer** [comment]
@ocefpaf This is more than I thought. I know of some windows users who might find this really cool, right @heistermann?

**Comment by kmuehlbauer** [comment]
@ocefpaf I do not see any things, not to merge. So if you haven't anything which holds this off, I can merge this later today, when the CI's are happy.

**Comment by ocefpaf** [comment]
> This is more than I thought. I know of some windows users who might find this really cool,

Indeed. My science (oceanography) still rely a lot on Fortran modules and I became a big fan of @carlkl's `mingwpy`. I am looking forward for the next release.

> I do not see any things, not to merge

Merge away :smile:

**Pull request merged**
